language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy

sudo: false

install:
  - pip install tox
  - pip install python-coveralls

script: tox

after_success:
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip
    - .tox
